---
- hosts: nodeexporter
  become: True
  become_user: root
  # vars:
  #     node_exporter_version: 1.1.2
  # vars_prompt:
  #         - name: "host"
  #           prompt: "Hostname"
  #           private: no
  tasks:
    - name: Transferring the Node Exporter File as per HW ( AMD )
      copy:
        src: ./files/amd_node
        dest: /usr/local/bin/node_exporter
        owner: root
        group: root
        mode: 0755
      when: (ansible_architecture == "x86_64") and (ansible_distribution == "Ubuntu") 
    - name: Transferring the Node Exporter File as per HW ( ARM64 )
      copy:
        src: ./files/arm_node
        dest: /usr/local/bin/node_exporter
        owner: root
        group: root
        mode: 0755
      when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu") 
    # - name: Allowing TCP:9100 Port for NodeExporter Via FirewallD
    #   ansible.posix.firewalld:
    #     port: 9100/tcp
    #     permanent: yes
    #     state: enabled
    - name: Creating SystemD File for Node Exporter
      template:
        src: ./templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0600
    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service
    #   get_url:
    #     # url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        
    #     dest: /tmp
    #   when: ansible_architecture == "x86_64"
    # - name: unarchive node exporter
    #   unarchive:
    #     remote_src: yes
    #     src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    #     dest: /tmp
    # - name: move node exporter to /usr/local/bin
    #   copy:
    #     src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    #     dest: /usr/local/bin/node_exporter
    #     remote_src: yes
    #     owner: root
    #     group: root
    #     mode: 0755
    # - name: install unit file to systemd
    #   template:
    #     src: ./files/node_exporter.service.j2
    #     dest: /etc/systemd/system/node_exporter.service
    #     owner: root
    #     group: root
    #     mode: 0600
    # - name: configure systemd to use service
    #   systemd:
    #     daemon_reload: yes
    #     enabled: yes
    #     state: started
    #     name: node_exporter.service